In [1]:
! pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Using cached soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\harsha\appdata\roaming\python\python311\site-packages (from beautifulsoup4) (4.15.0)
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
   ---------------------------------------- 0.0/109.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/109.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/109.9 kB ? eta -:--:--
   --- ------------------------------------ 10.2/109.9 kB ? eta -:--:--
   --- ------------------------------------ 10.2/109.9 kB ? eta -:--:--
   ------- ------------------------------- 20.5/109.9 kB 131.3 kB/s eta 0:00:01
   ---------- ---------------------------- 30.7/109.9 kB 186.2 kB/s eta 0:00:01
   --------------------- ----------------- 61.4/109.9 kB 297.7 kB/s eta 0:00:01
   ----------------------------------- -- 102.4/109.9 kB 392.2 kB/s eta 0:00:01
   -------------------------------------- 109.9/109.9 kB 398.7 kB/s eta 0:00:00
Using cached soupsieve-2.8.4-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, beautifulsoup4
Successfully installed beautifulsoup4-4.15.0 soupsieve-2.8.4

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
! pip install lxml

Collecting lxml
  Using cached lxml-6.1.1-cp311-cp311-win_amd64.whl.metadata (3.6 kB)
Using cached lxml-6.1.1-cp311-cp311-win_amd64.whl (4.0 MB)
Installing collected packages: lxml
Successfully installed lxml-6.1.1

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
! pip install html5lib

Collecting html5lib
  Using cached html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\users\harsha\appdata\roaming\python\python311\site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, html5lib
Successfully installed html5lib-1.1 webencodings-0.5.1

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
! pip install requests

Requirement already satisfied: requests in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (2.33.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from requests) (2026.2.25)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [107]:
from bs4 import BeautifulSoup
import requests

url = "https://in.hotels.com/ho327900/aalankrita-resort-and-convention-medchal-india/?chkin=2026-06-21&chkout=2026-06-22&x_pwa=1&rfrr=HSR&pwa_ts=1780993245177&referrerUrl=aHR0cHM6Ly9pbi5ob3RlbHMuY29tL0hvdGVsLVNlYXJjaA%3D%3D&rffrid=MDP.HCOM.IN.001.126.01.IN-DM_BMP.HtDtShP.X.kwrd%3DTAID757e0e4f-f16b-4ed8-8a2e-852acb397477.ade%3D.mbl%3DL.sic%3D2.dd%3D0.los%3D1.cin%3D2026-06-21.abw%3D12&useRewards=false&rm1=a2%3Ac0&regionId=6129087&destination=Shamirpet%2C%20Telangana%2C%20India&destType=MARKET&selected=8827353&latLong=17.591137%2C78.568426&mpo=EC&sort=RECOMMENDED&top_dp=6500&top_cur=INR&mctc=9&userIntent=&selectedRoomType=328694033&selectedRatePlan=409938253&expediaPropertyId=2957142&searchId=e91b2362-20d5-4a31-a028-efdeddb91034&pwaDialog=product-reviews"

source = requests.get(url)

In [108]:
print(source.status_code)
print(source.text[:500])

200
<!DOCTYPE html><html data-language="en_IN" dir="ltr" lang="en"><head><title></title><link rel="canonical" href="https://in.hotels.com/ho327900/aalankrita-resort-and-convention-medchal-india/"/><link rel="preconnect" href="https://images.trvl-media.com/"/><link rel="preconnect" href="https://maps.googleapis.com/"/><meta charSet="UTF-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><meta name="apple-mobile-web

In [111]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(source.text, "html.parser")

print(soup.get_text()[:5000])

Skip to main content Shop travelShop travelShop travel Hotels.com® RewardsOpen app

INRList your propertySupportTrips Communication Center  Sign in Members save 10% or more on over 100,000 hotels worldwide when you’re signed inSign inSign up, it’s freeFeedback     Where to?  Dates TravellersRoom 1AdultsDecrease the number of adults in room 1Increase the number of adults in room 1ChildrenAges 0 to 17Decrease the number of children in room 1Increase the number of children in room 1Child 1 ageUnder 11234567891011121314151617Add another roomNeed to book 9 or more rooms?DoneSearch  Photo gallery for Aalankrita Resort and ConventionExteriorInterior entranceProperty groundsOutdoor diningIndoor pool  75+  OverviewAboutRoomsAccessibilityPolicies  Aalankrita Resort and Convention3.5 star propertyReviews5.45.4 out of 10 See all 30 reviewsFamily-friendly highlights for your tripArcade/game roomA rare find - fun for all ages with on-site arcade and game room.About this propertyFamily-friendly hotel in Shamirpet with 3 restaurants and spa Kids’ poolAir-conditioningRestaurantPlayground on siteBuffet breakfast availableExtra bedsSee all about this propertyExplore the area View in a map Thumkunta Village, Karimnagar Main Road, Shameerpet Mandal, R.R. District, Shamirpet, Telangana, 500078View in a mapShamirpet LakePlace, Shamirpet Lake‪7 min drive‬Chicane circuitPlace, Chicane circuit‪8 min drive‬SNR Pushpa Convention CenterPlace, SNR Pushpa Convention Center‪11 min drive‬Hyderabad (HYD-Rajiv Gandhi Intl.)Airport, Hyderabad (HYD-Rajiv Gandhi Intl.)‪75 min drive‬See all about this areaChange Search Start dateEnd date Travellersprevnext    Loading

In [112]:
print("Anand" in source.text)
print("Narasimhulu" in source.text)
print("Radhika" in source.text)

False
False
False

In [113]:
import os

for file in os.listdir():
    print(file)

.env
main.ipynb
reviews.json

In [114]:
import os
print(os.getcwd())

c:\Users\Harsha\Downloads\sentiment analysis

In [115]:
import os

for file in os.listdir():
    print(file)

.env
main.ipynb
reviews.json

In [116]:
import json

with open("reviews.json", "r", encoding="utf-8") as f:
    data = json.load(f)

print(type(data))

<class 'list'>

In [117]:
print(data[0].keys())

dict_keys(['data', 'extensions'])

In [118]:
print(data[0]["data"].keys())

dict_keys(['productReviewDetails'])

In [119]:
print(data[0]["data"]["productReviewDetails"].keys())

dict_keys(['reviewsSectionHeading', 'sortAndFilter', '__typename', 'reviews'])

In [120]:
print(data[0]["data"]["productReviewDetails"]["reviews"].keys())

dict_keys(['impressionAnalytics', 'pagination', '__typename', 'noResultsMessage', 'details'])

In [121]:
import pandas as pd

reviews = data[0]["data"]["productReviewDetails"]["reviews"]["details"]

rows = []

for r in reviews:
    rows.append({
        "customer_name": r["summary"]["secondary"],
        "rating": r["summary"]["primary"],
        "review": r["review"]["text"],
        "stay_info": r["tripSummary"]["text"]
    })

df = pd.DataFrame(rows)

print(df.head())

  customer_name          rating  \
0         Anand  8/10 Very good
1          John       6/10 Good
2   Narasimhulu       2/10 Poor
3       Stephen       6/10 Good
4       Radhika       6/10 Good

                                              review  \
0  Nice resort for family staying and food qualit...
1  The first room had mold on the walls and was n...
2                           This is the worst hotel
3  Property is decent, but don’t expect a proper ...
4  Presidential suit is not what was advertised. ...

                    stay_info
0  Stayed 1 night in Jul 2022
1  Stayed 1 night in Jan 2026
2  Stayed 1 night in May 2025
3  Stayed 1 night in May 2023
4  Stayed 1 night in Dec 2024

In [122]:
df = df.drop(columns=["rating", "stay_info"])

print(df)

  customer_name                                             review
0         Anand  Nice resort for family staying and food qualit...
1          John  The first room had mold on the walls and was n...
2   Narasimhulu                           This is the worst hotel
3       Stephen  Property is decent, but don’t expect a proper ...
4       Radhika  Presidential suit is not what was advertised. ...
5       Rakeshh  The staff service is slow & extremely poor…One...
6       Sridhar                       Overall it didn’t look clean
7   Narasimhulu                                           not good
8   Narasimhulu                                           not good
9        Martin  Bel endroit où séjourner, satisfaction général...

In [123]:
pip install deep-translator

Requirement already satisfied: deep-translator in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (1.11.4)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from deep-translator) (4.15.0)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from deep-translator) (2.33.1)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\harsha\appdata\roaming\python\python311\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2026.2.25)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [128]:
from deep_translator import GoogleTranslator
import pandas as pd

translator = GoogleTranslator(source='auto', target='en')

def translate_text(text):
    try:
        return translator.translate(str(text))
    except Exception as e:
        print(f"Error: {e}")
        return text

df["review"] = df["review"].apply(translate_text)

In [129]:
print(df)

  customer_name                                             review
0         Anand  Nice resort for family staying and food qualit...
1          John  The first room had mold on the walls and was n...
2   Narasimhulu                            This is the worst hotel
3       Stephen  Property is decent, but don’t expect a proper ...
4       Radhika  Presidential suit is not what was advertised. ...
5       Rakeshh  The staff service is slow & extremely poor…One...
6       Sridhar                       Overall it didn’t look clean
7   Narasimhulu                                           not good
8   Narasimhulu                                           not good
9        Martin  Nice place to stay, overall satisfaction with ...

In [130]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_name  10 non-null     str
 1   review         10 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [131]:
df

  customer_name                                             review
0         Anand  Nice resort for family staying and food qualit...
1          John  The first room had mold on the walls and was n...
2   Narasimhulu                            This is the worst hotel
3       Stephen  Property is decent, but don’t expect a proper ...
4       Radhika  Presidential suit is not what was advertised. ...
5       Rakeshh  The staff service is slow & extremely poor…One...
6       Sridhar                       Overall it didn’t look clean
7   Narasimhulu                                           not good
8   Narasimhulu                                           not good
9        Martin  Nice place to stay, overall satisfaction with ...

In [132]:
! pip install python-dotenv openai

Requirement already satisfied: python-dotenv in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (1.2.2)
Requirement already satisfied: openai in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (2.32.0)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from openai) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from openai) (2.13.2)
Requirement already satisfied: sniffio in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\users\harsha\appdata\roaming\python\python311\site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from httpx<1,>=0.23.0->openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.2 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.46.2)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\harsha\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: colorama in c:\users\harsha\appdata\roaming\python\python311\site-packages (from tqdm>4->openai) (0.4.6)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [158]:
from dotenv import load_dotenv
import os
from openai import OpenAI

load_dotenv()

client = OpenAI(
    api_key=os.getenv("harsha_key"),
    base_url="https://api.groq.com/openai/v1"
)

In [159]:
response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {"role": "user", "content": "Say Hello"}
    ]
)

print(response.choices[0].message.content)

Hello. How can I assist you today?

In [160]:
cot_prompt = """
You are a sentiment analysis expert.

Follow these steps:

1. Identify all positive sentiment phrases.
2. Identify all negative sentiment phrases.
3. Check for contradictions or mixed sentiment.
4. Decide the final sentiment:
   Positive / Neutral / Negative.
5. Explain your reasoning step by step.

Examples:

Review:
"The hotel room was clean and spacious. Staff were friendly."

Reasoning:
Positive phrases:
- clean
- spacious
- friendly

Negative phrases:
- none

Mixed sentiment:
- no

Final Sentiment:
Positive

Explanation:
The review contains several positive descriptions and no complaints.

------------------------------------------------

Review:
"The room was okay. Nothing special."

Reasoning:
Positive phrases:
- okay

Negative phrases:
- none

Mixed sentiment:
- yes

Final Sentiment:
Neutral

Explanation:
The review does not express strong satisfaction or dissatisfaction.

------------------------------------------------

Review:
"The room was dirty and the service was slow."

Reasoning:
Positive phrases:
- none

Negative phrases:
- dirty
- slow

Mixed sentiment:
- no

Final Sentiment:
Negative

Explanation:
The review contains only negative experiences.

Now analyze:

Review:
{review}
"""

In [161]:
review = df["review"][0]

prompt = cot_prompt.replace("{review}", review)

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

print(response.choices[0].message.content)

To analyze the sentiment of the given review, I'll follow the steps outlined:

1. **Identify all positive sentiment phrases:**
   - Nice resort
   - food quality is also good

2. **Identify all negative sentiment phrases:**
   - none

3. **Check for contradictions or mixed sentiment:**
   - no contradictions or mixed sentiment are found in the review. The phrases used are consistently positive.

4. **Decide the final sentiment:**
   - Positive

5. **Explain my reasoning step by step:**
   The review mentions that the resort is "nice" for family stays, which implies a positive experience. Additionally, it highlights that the "food quality is also good," further emphasizing the positive aspects of the resort. Since there are no negative phrases or mixed sentiments expressed, the overall sentiment of the review is positive. The reviewer seems satisfied with their experience at the resort, citing both the suitability for families and the quality of the food as positive attributes.

In [162]:
results = []

for i, review in enumerate(df["review"], start=1):

    prompt = cot_prompt.replace("{review}", str(review))

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    output = response.choices[0].message.content

    print(f"\n{'='*50}")
    print(f"Review {i}")
    print(f"{'='*50}")
    print(output)

    results.append(output)

df["CoT_Output"] = results

==================================================
Review 1
==================================================
Reasoning:
Positive phrases:
- Nice resort
- good (food quality)

Negative phrases:
- none

Mixed sentiment:
- no

Final Sentiment:
Positive

Explanation:
The review contains several positive descriptions, including "Nice resort" which implies a pleasant and enjoyable experience, and "good" food quality, which suggests satisfaction with the culinary aspects of the resort. There are no complaints or negative experiences mentioned, indicating an overall positive sentiment towards the resort. The reviewer specifically mentions it being suitable for family stays, which further reinforces the positive sentiment.

==================================================
Review 2
==================================================
Reasoning:
Positive phrases:
- none

Negative phrases:
- mold on the walls
- not bearable to sleep in

Mixed sentiment:
- no

Final Sentiment:
Negative

Explanation:
The review contains only negative experiences, specifically mentioning the presence of mold on the walls and the room being unbearable to sleep in. This indicates a strongly negative sentiment, as it highlights significant issues with the room's condition and habitability. There are no positive or neutral phrases to balance out the negative comments, leading to an overall negative sentiment.

==================================================
Review 3
==================================================
Review:
"This is the worst hotel"

Reasoning:
Positive phrases:
- none

Negative phrases:
- worst

Mixed sentiment:
- no

Final Sentiment:
Negative

Explanation:
The review contains a strong negative statement, "worst hotel", which indicates a very low opinion of the hotel. There are no positive descriptions or mitigating factors to balance out the negative sentiment. The use of the superlative "worst" emphasizes the reviewer's strong dissatisfaction, leading to a clear negative final sentiment.

==================================================
Review 4
==================================================
Review:
Property is decent, but don’t expect a proper 4 star facility and service. A bit old school hospitality. Requires a lot of training for the staff too.

Reasoning:
Positive phrases:
- decent
- old school hospitality (this phrase can be seen as positive, depending on the context, as "old school" can imply traditional or classic)

Negative phrases:
- don’t expect a proper 4 star facility and service (implies that the facility and service are not up to 4-star standards)
- requires a lot of training for the staff (implies that the staff are not well-trained)

Mixed sentiment:
- yes (the review contains both positive and negative phrases, and also a negative implication of a positive phrase "decent" which is immediately followed by a negative statement)

Final Sentiment:
Neutral

Explanation:
The review expresses mixed sentiments. On one hand, it describes the property as "decent" and mentions "old school hospitality", which could be seen as positive. On the other hand, it expresses disappointment with the facility and service not being up to 4-star standards and criticizes the staff's training. The negative comments seem to outweigh the positive ones, but the tone is not strongly negative. The reviewer seems to have moderate expectations and is somewhat disappointed, but not extremely dissatisfied. Therefore, the final sentiment is Neutral.

==================================================
Review 5
==================================================
Reasoning:
Positive phrases:
- Pretty (this can be seen as a mild positive, but in this context, it's used to express "pretty average", which is more neutral than positive)

Negative phrases:
- not what was advertised
- average (implies that the experience did not exceed expectations)

Mixed sentiment:
- no

Final Sentiment:
Negative

Explanation:
The review expresses dissatisfaction with the Presidential suit not meeting the advertised expectations. Although the phrase "pretty average" might seem neutral, in the context of a high-end service like a Presidential suit, it implies a letdown. The negative sentiment of the suite not meeting expectations outweighs any mild positive undertone, leading to an overall negative sentiment.

==================================================
Review 6
==================================================
Review:
The staff service is slow & extremely poor…One of the worst I have ever seen…Their attitude sucks & constant reminders need to be provided for room clearance and service.

Reasoning:
Positive phrases:
- none

Negative phrases:
- slow
- extremely poor
- one of the worst
- attitude sucks
- constant reminders (implying inefficiency)

Mixed sentiment:
- no

Final Sentiment:
Negative

Explanation:
The review expresses strong dissatisfaction with the staff service, calling it "slow" and "extremely poor". The phrase "one of the worst" emphasizes the reviewer's negative experience. Additionally, the staff's "attitude sucks", which further adds to the negative sentiment. The need for "constant reminders" for basic services like room clearance also implies poor service quality. Since there are no positive phrases or mixed sentiment, the final sentiment is clearly negative, indicating a strongly unfavorable review.

==================================================
Review 7
==================================================
Reasoning:
Positive phrases:
- none

Negative phrases:
- didn’t look clean

Mixed sentiment:
- no

Final Sentiment:
Negative

Explanation:
The review contains a negative description of the hotel's cleanliness, which indicates a clear dissatisfaction. The phrase "didn’t look clean" expresses a strong negative sentiment, and there are no positive phrases to balance it out. Therefore, the final sentiment of the review is Negative.

==================================================
Review 8
==================================================
Review: not good

Reasoning:
Positive phrases:
- none

Negative phrases:
- not good

Mixed sentiment:
- no

Final Sentiment:
Negative

Explanation:
The review contains a clear negative statement ("not good") with no positive or neutral comments to balance it out. The phrase "not good" directly expresses dissatisfaction, leading to a negative final sentiment.

==================================================
Review 9
==================================================
Review: not good

Reasoning:
Positive phrases:
- none

Negative phrases:
- not good

Mixed sentiment:
- no

Final Sentiment:
Negative

Explanation:
The review contains a clear negative statement ("not good") with no positive descriptions to balance it. The phrase "not good" directly expresses dissatisfaction, leading to an overall negative sentiment.

==================================================
Review 10
==================================================
Review:
Nice place to stay, overall satisfaction with my stay.
Comfortable room (very good bed) and relatively quiet (wedding during my stay, so quite noisy on an evening).
Very good restaurant.
However, poor wifi makes it practically impossible to hold a video meeting. Water more lukewarm than hot for the shower.

Reasoning:
Positive phrases:
- Nice place to stay
- overall satisfaction
- Comfortable room
- very good bed
- relatively quiet
- Very good restaurant

Negative phrases:
- poor wifi
- lukewarm water (instead of hot)

Mixed sentiment:
- yes (the phrase "relatively quiet" implies that it was not completely quiet, which is a mixed sentiment, and the reviewer mentions a wedding making it noisy in the evening)

Final Sentiment:
Neutral

Explanation:
The review contains both positive and negative experiences. The reviewer expresses satisfaction with their stay, comfort, and the restaurant. However, they also mention significant issues with the wifi and water temperature. The mixed sentiment phrase "relatively quiet" suggests that the reviewer had some noise disturbance but found it manageable. Given the balance of positive and negative comments, the final sentiment is Neutral. The reviewer's "overall satisfaction" is somewhat tempered by the significant issues they experienced, preventing the sentiment from being outright Positive.

# choosing right paramters using Tree-of-thought

In [ ]:

import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [167]:
data = load_breast_cancer()

X = data.data
y = data.target

In [168]:
param_grid = {
    "n_estimators":[50,100,150],
    "max_depth":[3,5,10],
    "min_samples_split":[2,5]
}

In [169]:
rf = RandomForestClassifier(random_state=42)

grid = GridSearchCV(
    rf,
    param_grid,
    cv=5,
    scoring="accuracy",
    return_train_score=True
)

grid.fit(X,y)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [3, 5, 10], 'min_samples_split': [2, 5],
                         'n_estimators': [50, 100, 150]},
             return_train_score=True, scoring='accuracy')

In [174]:
type(results)

list

In [175]:
import pandas as pd

tuning_results = pd.DataFrame(grid.cv_results_)

tuning_results = tuning_results[
[
    "param_n_estimators",
    "param_max_depth",
    "param_min_samples_split",
    "mean_test_score",
    "mean_train_score",
    "mean_fit_time"
]
]

tuning_results["overfit_gap"] = (
    tuning_results["mean_train_score"]
    -
    tuning_results["mean_test_score"]
)

tuning_results.head()

,param_n_estimators,param_max_depth,param_min_samples_split,mean_test_score,mean_train_score,mean_fit_time,overfit_gap
0,50,3,2,0.954324,0.976277,0.093326,0.021953
1,100,3,2,0.954324,0.977153,0.191864,0.022830
2,150,3,2,0.952569,0.977592,0.281184,0.025023
3,50,3,5,0.954324,0.975838,0.089196,0.021514
4,100,3,5,0.954324,0.976715,0.179806,0.022391

In [176]:
tuning_results = tuning_results.sort_values(
    by="mean_test_score",
    ascending=False
)

tuning_results.head(10)

,param_n_estimators,param_max_depth,param_min_samples_split,mean_test_score,mean_train_score,mean_fit_time,overfit_gap
15,50,10,5,0.963127,0.996925,0.118377,0.033798
9,50,5,5,0.959618,0.993409,0.106262,0.033791
16,100,10,5,0.959618,0.996046,0.226469,0.036428
7,100,5,2,0.959618,0.993849,0.219381,0.034231
8,150,5,2,0.959603,0.993409,0.330732,0.033807
17,150,10,5,0.959603,0.996485,0.770228,0.036883
10,100,5,5,0.957864,0.993409,0.221199,0.035546
11,150,5,5,0.957864,0.992970,0.320685,0.035106
14,150,10,2,0.956094,1.000000,0.336173,0.043906
13,100,10,2,0.956094,1.000000,0.224526,0.043906

In [177]:
results_text = tuning_results.to_string(index=False)

In [180]:
tot_prompt = f"""
You are a Machine Learning expert.

Analyze the Random Forest hyperparameter tuning results using Tree-of-Thought reasoning.

Structure your answer exactly as follows:

## Thought Branch A (max_depth = 3)

For each configuration:
- Validation Accuracy
- Training Time
- Overfitting Gap
- Bias-Variance Analysis

Then summarize:
- Strengths
- Weaknesses
- Best candidate in Branch A

## Thought Branch B (max_depth = 5)

For each configuration:
- Validation Accuracy
- Training Time
- Overfitting Gap
- Bias-Variance Analysis

Then summarize:
- Strengths
- Weaknesses
- Best candidate in Branch B

## Thought Branch C (max_depth = 10)

For each configuration:
- Validation Accuracy
- Training Time
- Overfitting Gap
- Bias-Variance Analysis

Then summarize:
- Strengths
- Weaknesses
- Best candidate in Branch C

## Final Comparison

Create a comparison table containing:
- Configuration
- Validation Accuracy
- Overfitting Gap
- Training Time

Compare the best candidate from each branch.

## Final Decision

Clearly state:

Best Hyperparameter Configuration:
- n_estimators = ?
- max_depth = ?
- min_samples_split = ?

Justification:
- Why this configuration was selected
- Why other candidates were rejected
- Discussion of accuracy, overfitting risk, and computational cost

Hyperparameter Results:

{results_text}
"""

In [181]:
response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {"role":"user","content":tot_prompt}
    ]
)

print(response.choices[0].message.content)

## Thought Branch A (max_depth = 3)

For each configuration:
- Validation Accuracy: 0.954324 (for n_estimators = 100, min_samples_split = 2), 0.954324 (for n_estimators = 100, min_samples_split = 5), 0.954324 (for n_estimators = 50, min_samples_split = 2), 0.954324 (for n_estimators = 50, min_samples_split = 5), 0.952569 (for n_estimators = 150, min_samples_split = 2), 0.952569 (for n_estimators = 150, min_samples_split = 5)
- Training Time: 0.191864 (for n_estimators = 100, min_samples_split = 2), 0.179806 (for n_estimators = 100, min_samples_split = 5), 0.093326 (for n_estimators = 50, min_samples_split = 2), 0.089196 (for n_estimators = 50, min_samples_split = 5), 0.281184 (for n_estimators = 150, min_samples_split = 2), 0.271636 (for n_estimators = 150, min_samples_split = 5)
- Overfitting Gap: 0.022830 (for n_estimators = 100, min_samples_split = 2), 0.022391 (for n_estimators = 100, min_samples_split = 5), 0.021953 (for n_estimators = 50, min_samples_split = 2), 0.021514 (for n_estimators = 50, min_samples_split = 5), 0.025023 (for n_estimators = 150, min_samples_split = 2), 0.024145 (for n_estimators = 150, min_samples_split = 5)
- Bias-Variance Analysis: The models with max_depth = 3 have a relatively low overfitting gap, indicating a good balance between bias and variance.

Then summarize:
- Strengths: Low overfitting gap, relatively fast training time.
- Weaknesses: Lower validation accuracy compared to other branches.
- Best candidate in Branch A: n_estimators = 100, max_depth = 3, min_samples_split = 2, with a validation accuracy of 0.954324 and an overfitting gap of 0.022830.

## Thought Branch B (max_depth = 5)

For each configuration:
- Validation Accuracy: 0.959618 (for n_estimators = 50, min_samples_split = 5), 0.959618 (for n_estimators = 100, min_samples_split = 2), 0.959618 (for n_estimators = 100, min_samples_split = 5), 0.959603 (for n_estimators = 150, min_samples_split = 2), 0.959603 (for n_estimators = 150, min_samples_split = 5), 0.957864 (for n_estimators = 100, min_samples_split = 5), 0.957864 (for n_estimators = 150, min_samples_split = 5), 0.956078 (for n_estimators = 50, min_samples_split = 2)
- Training Time: 0.106262 (for n_estimators = 50, min_samples_split = 5), 0.219381 (for n_estimators = 100, min_samples_split = 2), 0.221199 (for n_estimators = 100, min_samples_split = 5), 0.330732 (for n_estimators = 150, min_samples_split = 2), 0.320685 (for n_estimators = 150, min_samples_split = 5), 0.114229 (for n_estimators = 50, min_samples_split = 2)
- Overfitting Gap: 0.033791 (for n_estimators = 50, min_samples_split = 5), 0.034231 (for n_estimators = 100, min_samples_split = 2), 0.035546 (for n_estimators = 100, min_samples_split = 5), 0.033807 (for n_estimators = 150, min_samples_split = 2), 0.035106 (for n_estimators = 150, min_samples_split = 5), 0.039089 (for n_estimators = 50, min_samples_split = 2)
- Bias-Variance Analysis: The models with max_depth = 5 have a relatively high overfitting gap, indicating a potential issue with overfitting.

Then summarize:
- Strengths: High validation accuracy.
- Weaknesses: Relatively high overfitting gap, longer training time.
- Best candidate in Branch B: n_estimators = 50, max_depth = 5, min_samples_split = 5, with a validation accuracy of 0.959618 and an overfitting gap of 0.033791.

## Thought Branch C (max_depth = 10)

For each configuration:
- Validation Accuracy: 0.963127 (for n_estimators = 50, min_samples_split = 5), 0.959618 (for n_estimators = 100, min_samples_split = 5), 0.959603 (for n_estimators = 150, min_samples_split = 5), 0.956094 (for n_estimators = 100, min_samples_split = 2), 0.956094 (for n_estimators = 150, min_samples_split = 2), 0.954324 (for n_estimators = 50, min_samples_split = 2)
- Training Time: 0.118377 (for n_estimators = 50, min_samples_split = 5), 0.226469 (for n_estimators = 100, min_samples_split = 5), 0.770228 (for n_estimators = 150, min_samples_split = 5), 0.224526 (for n_estimators = 100, min_samples_split = 2), 0.336173 (for n_estimators = 150, min_samples_split = 2), 0.106582 (for n_estimators = 50, min_samples_split = 2)
- Overfitting Gap: 0.033798 (for n_estimators = 50, min_samples_split = 5), 0.036428 (for n_estimators = 100, min_samples_split = 5), 0.036883 (for n_estimators = 150, min_samples_split = 5), 0.043906 (for n_estimators = 100, min_samples_split = 2), 0.043906 (for n_estimators = 150, min_samples_split = 2), 0.045676 (for n_estimators = 50, min_samples_split = 2)
- Bias-Variance Analysis: The models with max_depth = 10 have a relatively high overfitting gap, indicating a potential issue with overfitting.

Then summarize:
- Strengths: High validation accuracy.
- Weaknesses: High overfitting gap, long training time.
- Best candidate in Branch C: n_estimators = 50, max_depth = 10, min_samples_split = 5, with a validation accuracy of 0.963127 and an overfitting gap of 0.033798.

## Final Comparison

| Configuration | Validation Accuracy | Overfitting Gap | Training Time |
| --- | --- | --- | --- |
| n_estimators = 100, max_depth = 3, min_samples_split = 2 | 0.954324 | 0.022830 | 0.191864 |
| n_estimators = 50, max_depth = 5, min_samples_split = 5 | 0.959618 | 0.033791 | 0.106262 |
| n_estimators = 50, max_depth = 10, min_samples_split = 5 | 0.963127 | 0.033798 | 0.118377 |

Compare the best candidate from each branch:
The best candidate from Branch A has a lower validation accuracy but a lower overfitting gap. The best candidate from Branch B has a higher validation accuracy but a higher overfitting gap. The best candidate from Branch C has the highest validation accuracy but a higher overfitting gap and longer training time.

## Final Decision

Best Hyperparameter Configuration:
- n_estimators = 50
- max_depth = 10
- min_samples_split = 5

Justification:
- This configuration was selected because it has the highest validation accuracy (0.963127) among all configurations.
- Other candidates were rejected because they have lower validation accuracy or higher overfitting gaps.
- The configuration with n_estimators = 50, max_depth = 10, min_samples_split = 5 has a good balance between accuracy and overfitting risk, and its training time is relatively short (0.118377). However, it is worth noting that this configuration has a higher overfitting gap compared to the best candidate in Branch A, which may indicate a potential issue with overfitting. But given the high validation accuracy, this configuration is still the best choice.